apiVersion: v1
kind: ConfigMap
metadata:
  name: a-configmap
data:
  foo: "" # kpt-set: ${foo}
  bar: "" # kpt-set: ${bar}
  baz: "" # kpt-set: ${baz}
  replicas: "" # kpt-set: ${deployReplicas}
  combined: "" # kpt-set: ${deployReplicas}-${bar}
